version = 1

[[annotations]]
path = ["*.md", ".gitignore"]
precedence = "closest"
SPDX-FileCopyrightText = "Â© 2025 Clifford Weinmann <https://www.cliffordweinmann.com/>"
SPDX-License-Identifier = "MIT-0"
